environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
build:
  - cmake. -G "Visual Studio 16 2019"  # 根据选择的VS版本调整
  - cmake --build.
  - ctest -C Debug
